<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!--Define the mod's info.json-->
		<ModName>Concert Rebalance</ModName>
		<HarmonyID>com.tel.concertrebalance</HarmonyID>
		<ModDescription>Rebalances concerts to make things more challenging.</ModDescription>
		<Authors>Tel</Authors>
		<Version>1.2.0</Version>
		<WorkshopID>2977860534</WorkshopID>
		<Tags>["gameplay"]</Tags>

		<!--For the JSON Load Order mod (leave it at 0 if not using)-->
		<JSONLoadOrder>0</JSONLoadOrder>
	</PropertyGroup>
	
</Project>
