<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!--Define the mod's info.json-->
		<ModName>MBTI Personalities</ModName>
		<HarmonyID>com.tel.mbtipersonalities</HarmonyID>
		<ModDescription>Randomly assigns MBTI types to girls, which have minor gameplay effects.</ModDescription>
		<Authors>Tel</Authors>
		<Version>1.3.0</Version>
		<WorkshopID>2982853830</WorkshopID>
		<Tags>["gameplay"]</Tags>

		<!--For the JSON Load Order mod (leave it at 0 if not using)-->
		<JSONLoadOrder>0</JSONLoadOrder>
	</PropertyGroup>

	<Import Project="..\..\shared\StatLimits\StatLimits.projitems" Label="Shared" />

</Project>
