<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!--Define the mod's info.json-->
		<ModName>Tour Stamina Limit</ModName>
		<HarmonyID>com.tel.tourstamina</HarmonyID>
		<ModDescription>World Tour has a 100 stamina limit. Fans increased 3.5x to compensate.</ModDescription>
		<Authors>Tel</Authors>
		<Version>1.0.1</Version>
		<WorkshopID>2977861566</WorkshopID>
		<Tags>["gameplay"]</Tags>

		<!--For the JSON Load Order mod (leave it at 0 if not using)-->
		<JSONLoadOrder>0</JSONLoadOrder>
	</PropertyGroup>

</Project>
