<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!--Define the mod's info.json-->
		<ModName>National Tour</ModName>
		<HarmonyID>com.tel.nationaltour</HarmonyID>
		<ModDescription>Replaces World Tours with National Tours.</ModDescription>
		<Authors>Tel</Authors>
		<Version>2.1.1</Version>
		<WorkshopID>2872425710</WorkshopID>
		<Tags>["gameplay"]</Tags>

		<!--For the JSON Load Order mod (leave it at 0 if not using)-->
		<JSONLoadOrder>0</JSONLoadOrder>
	</PropertyGroup>

</Project>
