<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!--Define the mod's info.json-->
		<ModName>FastForward</ModName>
		<HarmonyID>com.tel.fastforward</HarmonyID>
		<ModDescription>Press '4' or click the fast-forward button twice to go faster!</ModDescription>
		<Authors>Tel</Authors>
		<Version>1.3.1</Version>
		<WorkshopID>2976136928</WorkshopID>
		<Tags>["gameplay"]</Tags>

		<!--For the JSON Load Order mod (leave it at 0 if not using)-->
		<JSONLoadOrder>0</JSONLoadOrder>
	</PropertyGroup>

</Project>
