<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!--Define the mod's info.json-->
		<ModName>Menu Hotkeys</ModName>
		<HarmonyID>com.tel.menuhotkeys</HarmonyID>
		<ModDescription>Home row on the keyboard (asdfg...) are hotkeys for the main menu.</ModDescription>
		<Authors>Tel</Authors>
		<Version>1.0.1</Version>
		<WorkshopID>2976589114</WorkshopID>
		<Tags>["gameplay"]</Tags>

		<!--For the JSON Load Order mod (leave it at 0 if not using)-->
		<JSONLoadOrder>0</JSONLoadOrder>
	</PropertyGroup>

</Project>
