<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!--Define the mod's info.json-->
		<ModName>Stale Theater Shows</ModName>
		<HarmonyID>com.tel.staletheater</HarmonyID>
		<ModDescription>Rebalances the theater. Theater shows go stale over time. Release a single every month to keep the theater shows fresh.</ModDescription>
		<Authors>Tel</Authors>
		<Version>1.1.1</Version>
		<WorkshopID>2977861222</WorkshopID>
		<Tags>["gameplay"]</Tags>

		<!--For the JSON Load Order mod (leave it at 0 if not using)-->
		<JSONLoadOrder>0</JSONLoadOrder>
	</PropertyGroup>

</Project>
