<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!--Define the mod's info.json-->
		<ModName>Policies That Matter</ModName>
		<HarmonyID>com.tel.policiesthatmatter</HarmonyID>
		<ModDescription>Makes policies have more impact on gameplay. Take care to manage the mental stamina!</ModDescription>
		<Authors>Tel</Authors>
		<Version>1.2.0</Version>
		<WorkshopID>2977861066</WorkshopID>
		<Tags>["gameplay"]</Tags>

		<!--For the JSON Load Order mod (leave it at 0 if not using)-->
		<JSONLoadOrder>0</JSONLoadOrder>
	</PropertyGroup>

</Project>
