<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!--Define the mod's info.json-->
		<ModName>Unofficial Patch</ModName>
		<HarmonyID>com.tel.unofficialpatch</HarmonyID>
		<ModDescription>Unofficial bugfixes</ModDescription>
		<Authors>Tel</Authors>
		<Version>1.6.1</Version>
		<WorkshopID>2976384244</WorkshopID>
		<Tags>["gameplay"]</Tags>

		<!--For the JSON Load Order mod (leave it at 0 if not using)-->
		<JSONLoadOrder>0</JSONLoadOrder>
	</PropertyGroup>

</Project>
