<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!--Define the mod's info.json-->
		<ModName>Worker Rights</ModName>
		<HarmonyID>com.tel.workerrights</HarmonyID>
		<ModDescription>Employee rights! Idols will demand fair wages! Brand new staff cannot be blamed for scandals!</ModDescription>
		<Authors>Tel</Authors>
		<Version>1.1.0</Version>
		<WorkshopID>2977860966</WorkshopID>
		<Tags>["gameplay"]</Tags>

		<!--For the JSON Load Order mod (leave it at 0 if not using)-->
		<JSONLoadOrder>0</JSONLoadOrder>
	</PropertyGroup>

</Project>
