<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!--Define the mod's info.json-->
		<ModName>Traits Expansion</ModName>
		<HarmonyID>com.tel.traitsexpansion</HarmonyID>
		<ModDescription>A bunch of new traits that expand upon the existing set of traits. They affect stats, appeal, businesses, special events and more.</ModDescription>
		<Authors>Tel</Authors>
		<Version>1.1.2</Version>
		<WorkshopID>2985475895</WorkshopID>
		<Tags>["gameplay"]</Tags>

		<!--For the JSON Load Order mod (leave it at 0 if not using)-->
		<JSONLoadOrder>0</JSONLoadOrder>
	</PropertyGroup>

	<Import Project="..\..\shared\StatLimits\StatLimits.projitems" Label="Shared" />

</Project>
