<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!--Define the mod's info.json-->
		<ModName>Star Signs</ModName>
		<HarmonyID>com.tel.starsigns</HarmonyID>
		<ModDescription>Adds zodiac signs for some flavor and minor effects to girls' relationships.</ModDescription>
		<Authors>Tel</Authors>
		<Version>1.1.1</Version>
		<WorkshopID>2981776133</WorkshopID>
		<Tags>["gameplay"]</Tags>

		<!--For the JSON Load Order mod (leave it at 0 if not using)-->
		<JSONLoadOrder>0</JSONLoadOrder>
	</PropertyGroup>

</Project>
