<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!--Define the mod's info.json-->
		<ModName>Promotion Tier Tweaks</ModName>
		<HarmonyID>com.tel.promotiontiertweaks</HarmonyID>
		<ModDescription>The criteria for promotion levelups increased to be more challenging.</ModDescription>
		<Authors>Tel</Authors>
		<Version>1.1.0</Version>
		<WorkshopID>2978159435</WorkshopID>
		<Tags>["gameplay"]</Tags>

		<!--For the JSON Load Order mod (leave it at 0 if not using)-->
		<JSONLoadOrder>0</JSONLoadOrder>
	</PropertyGroup>

</Project>
